# Generated by Django 3.2.9 on 2023-03-24 06:49

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0009_auto_20230322_1628'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='secondary_business',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Wholesaler', 'Wholesaler'), ('Exporter', 'Exporter'), ('Distributor', 'Distributor'), ('Non Profit Organization', 'Non Profit Organization'), ('Association', 'Association'), ('Supplier', 'Supplier'), ('Buyer Individual', 'Buyer Individual'), ('Service Provider', 'Service Provider'), ('Importer', 'Importer')], default='Wholesaler', max_length=119),
        ),
    ]
