# Generated by Django 3.2.9 on 2023-03-28 10:29

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0011_auto_20230328_1002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='secondary_business',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Importer', 'Importer'), ('Exporter', 'Exporter'), ('Manufacturer', 'Manufacturer'), ('Wholesaler/Dealer/Distributor', 'Wholesaler/Dealer/Distributor'), ('Retailer', 'Retailer')], default='Wholesaler/Dealer/Distributor', max_length=69),
        ),
    ]
