# Generated by Django 3.2.9 on 2023-03-31 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0012_alter_supplier_secondary_business'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='facebook',
            field=models.URLField(blank=True, max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='instagram',
            field=models.URLField(blank=True, max_length=400, null=True),
        ),
    ]
