# Generated by Django 3.2.9 on 2023-04-09 02:18

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0013_auto_20230331_0624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='secondary_business',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Importer', 'Importer'), ('Exporter', 'Exporter'), ('Manufacturer', 'Manufacturer'), ('Wholesaler/Dealer/Distributor', 'Wholesaler/Dealer/Distributor'), ('Retailer', 'Retailer'), ('Service Provider', 'Service Provider')], default='Wholesaler/Dealer/Distributor', max_length=86),
        ),
    ]
