"""
Django settings for vistaar project.

Generated by 'django-admin startproject' using Django 3.1.4.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""

from pathlib import Path
import os
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '4of_7mm^8ei^o4acfxm2b*5gci15r08m)0=e@fgs1n$oz!!s7@'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']
INTERNAL_IPS = ['127.0.0.1']

# Application definition

INSTALLED_APPS = [
    'debug_toolbar',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    #own apps
    'products',
    'orders',
    'suppliers',
    'request',

    'account.apps.AccountConfig',
    'ckeditor',
    'reviews',

]

MIDDLEWARE = [
    "debug_toolbar.middleware.DebugToolbarMiddleware",
    'django.middleware.security.SecurityMiddleware',

    'whitenoise.middleware.WhiteNoiseMiddleware',

    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'vistaar.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / "templates"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'products.context_processor.extras'

            ],
        },
    },
]

WSGI_APPLICATION = 'vistaar.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.1/ref/settings/#databases
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'vistraat_backup-4-18',
        'USER': 'db_admin',
        'PASSWORD': 'dbvistaar1234',
        'HOST': 'vistaar-db.cicssufokwpy.ap-south-1.rds.amazonaws.com',
        'PORT': '3306',
    }
}

#DATABASES = {
#    'default': {
#        'ENGINE': 'django.db.backends.mysql',
#
#        'NAME': 'your_database_name_here',
#
#        'USER': 'your_username_here',
#
#        'PASSWORD': 'your_password_here',
#
#        'HOST': 'localhost',
#
#        'PORT': '3306',
#
#    }
#}


# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.mysql',

#         'NAME': 'vistraat_db',

#         'USER': 'vistraat_sqluser',

#         'PASSWORD': ';GIXZ+D@6pzn',

#         'HOST': 'localhost',

#         'PORT': '3306',

#     }
# }

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.postgresql_psycopg2',

#         'NAME': 'vistraat_vistaardb',

#         'USER': 'vistraat_dbuser',

#         'PASSWORD': 'Ysj~tQWA^@3;',

#         'HOST': 'localhost',

#         'PORT': '5432',

#     }
# }

#DATABASES = {
#    'default': {
#        'ENGINE': 'django.db.backends.sqlite3',
#        'NAME': BASE_DIR / 'db.sqlite3',
#    }
#}


# Password validation
# https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.1/howto/static-files/

STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static'),'/home/ubuntu/vistaar/my_env/lib/python3.10/site-packages/django/contrib/admin/static']
STATIC_URL = '/static/'

#Accounts App Login

LOGIN_REDIRECT_URL = "/" 
LOGIN_URL = 'login'

#Email-Backend

#EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

#Email-Config
EMAIL_HOST = 'smtp.office365.com'
EMAIL_HOST_USER = 'account@vistaartrade.com'
EMAIL_FROM_USER = 'account@vistaartrade.com'
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER
EMAIL_HOST_PASSWORD = 'ForNepal123'
EMAIL_PORT = 587
EMAIL_USE_SSL = False
EMAIL_USE_TLS = True


#Media Files

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')



