# Generated by Django 3.2.9 on 2023-05-12 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_products_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='seller_top_product',
            field=models.BooleanField(default=False),
        ),
    ]
